### ISSUE TITLE
Question: Two jobs (build and then deploy) behind one trigger?

### ISSUE THREAD

**Issue by pandemicsyn** [github/branch-deploy#102]
Apologies in advance if this is a dumb question but having a hard time wrapping my head around it.

I'm migrating from a merge deploy based workflow with two jobs. I've got a build job that does a matrix to build and push some images to a container registry, and then a second job that performs the actual deploy of the images from the `build` job. 

Something like:

```
jobs:
  build:
    if: <if main or dev && is a push>
    strategy:
      matrix:
    ...
    steps:
     <build a bunch of images and push them to a registry>

  deploy:
    if: <if main or dev && is a push>
    needs: build
    steps:
      <reference some output from build, and call some deployment steps, tf plan etc>
```

What's the best way to transition these to using the branch-deploy action and have them execute sequentially? 

Can I just use the branch-deploy action with the same keyword trigger on each job - and then keep the `needs` requirement of the second job? Do I need to merge these two jobs into a single one? Or should I have two discrete keyword triggers for each e.g. `.build` and `.deploy`?
