### ISSUE TITLE
Unlock environments on pull request merge

### ISSUE THREAD

**Issue by bzurkowski** [github/branch-deploy#148]
### Describe the Issue

I am trying to recreate the **locking feature** of the [Atlantis workflow](https://www.runatlantis.io/) using the branch-deploy action.

In Atlantis, it is possible to configure a workflow behavior where a lock is acquired on `terraform plan` for a set of directories, and the lock is released after the pull request is successfully merged into the main branch. 

When running `terraform apply` before a pull request is merged, the main branch ceases to represent the most current version of the infrastructure. Locking ensures no further changes occur until the PR is merged, keeping the infrastructure representation intact. More reasoning behind this concept is well explained in Atlantis [documentation](https://www.runatlantis.io/docs/locking.html).

I believe incorporating a similar locking feature would be a significant improvement for Terraform users of this action. This is particularly relevant given that Terraform is showcased as one of the main usage examples.

When using the branch-deploy action, it is easy to implement the first part of the locking feature, i.e., acquire a lock on `terraform plan` (or `apply`) using the [lock](https://github.com/github/lock) action. However, it is problematic to release the lock on the pull request merge (e.g., using the `on: pull_request[closed]` trigger). **The main difficulty lies in obtaining the list of active locks to release.**

I would genuinely appreciate any insights you might have on implementing this functionality. Perhaps, I missed some details in the documentation or usage examples.

**Comment by bzurkowski** [comment]
I managed to implement this using the following workflow configuration:

```yaml
name: Release deployment locks

on:
  pull_request:
    types: [closed]

permissions:
  deployments: read
  contents: write

jobs:
  release-locks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove active deployment locks
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          environments=$(gh api "/repos/{owner}/{repo}/deployments?ref=${{ github.head_ref }}" | jq -r '.[].environment | select(. != null)' | uniq)

          for environment in $environments; do
              lock_branch="$environment-branch-deploy-lock"

              echo "Checking lock: $lock_branch"
              if gh api --method GET "repos/{owner}/{repo}/git/refs/heads/$lock_branch" > /dev/null 2>&1; then
                  echo "Deleting lock: $lock_branch"
                  gh api --method DELETE "repos/{owner}/{repo}/git/refs/heads/$lock_branch"
              else
                  echo "Lock does not exist: $lock_branch"
              fi
          done
```
