### ISSUE TITLE
Users with role 'maintain' cannot trigger deployments

### ISSUE THREAD

**Issue by juboe-kion** [github/branch-deploy#156]
### Describe the Issue

Hi! We're using this action in our organization, but are currently facing an issue with some users who have the `maintain` role. 

### Problem description
It seems that when a user (only?) has the `maintain` role, he is not allowed to run commands using this action. When a deploy is triggered by a user with this permission, the following message appears:
> 👋 *actor*, seems as if you have not admin/write permissions in this repo, permissions: maintain

However, if I understand the [GitHub docs](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations) correctly, this role should sit between the `Write` and `Admin` roles. Thus, we'd also expect a user with this role to be able to trigger deployments.

### Probable root cause
Seems like the values `admin` and `write` are hard-coded in the `valid-permissions.js` file:
```js
  // Check to ensure the user has at least write permission on the repo
  const actorPermission = permissionRes.data.permission
  if (!['admin', 'write'].includes(actorPermission)) {
    return `👋 __${context.actor}__, seems as if you have not admin/write permissions in this repo, permissions: ${actorPermission}`
  }
```

### Action Configuration

```yaml
on:
  issue_comment:
    types: [created, edited]

jobs:
  trigger:
    if: ${{ github.event.issue.pull_request && github.actor != 'xyz' }}
    runs-on: ubuntu-latest
    steps:
      - uses: github/branch-deploy@v5.2.1
        id: branch-deploy
        with:
          trigger: ".deploy-xyz"
          environment: dev-xyz
          environment_targets: dev-xyz
          update_branch: disabled
          skip_reviews: dev-xyz
          skip_ci: dev-xyz
          skip_completing: "true"
          lock_trigger: ".lock-xyz"
          unlock_trigger: ".unlock-xyz"
```

### Relevant Actions Log Output

> Error: 👋 __xyz__, seems as if you have not admin/write permissions in this repo, permissions: maintain
