### ISSUE TITLE
Use branch deploy together with 

### ISSUE THREAD

**Issue by hansarh** [github/branch-deploy#159]

**Comment by GrantBirki** [comment]
@hansarh Would you be able to construct the `role-to-assume` value with the outputs from the branch-deploy Action? It looks like you need it in the following format: `repo:z<org>/<reponame>:environment:beta`

Since the [`environment`](https://github.com/github/branch-deploy/blob/21a822a5da309dbc82276cd4a5fb51bc557620d8/action.yml#L121) is an output of this Action, could you use it to construct that value?

Example:

```yaml
with:
      role-to-assume: "z<org>/<reponame>:environment:${{ steps.branch-deploy.outputs.environment }}"
      aws-region: eu-west-1
```
