### ISSUE TITLE
Prefixing environments internally

### ISSUE THREAD

**Issue by bzurkowski** [github/branch-deploy#168]
### Details

I handle infrastructure code (Terraform) in a mono-repo, which necessitates the deployment of numerous projects across various environments from a single repository. 

I managed to implement a separate branch-deployment gate for each project using distinct triggers:

```yaml
trigger:
  if: |
    github.event.issue.pull_request
  runs-on: ubuntu-latest
  steps:
    - name: Gate branch deployment
      id: branch-deploy
      uses: github/branch-deploy@v6.0.0
      with:
        trigger: .deploy ${{ inputs.project_name }}
        noop_trigger: plan
```

The above configuration produces the following IssueOps interface:

```
.deploy foo dev/staging/prod
.deploy foo plan dev/staging/prod

.deploy bar dev/staging/prod
.deploy bar plan dev/staging/prod
```

However, given multiple projects, specified environments, i.e., `dev/staging/prod`, are "shared" (from the `branch-deploy` action's perspective), which implies that whenever I deploy to project `foo`, corresponding Github environments are being locked and altered with deployment status, preventing me against deploying to the `boo` project from other pull requests.

Consequently, in a mono-repo setup, one must distinguish Github environments by project, e.g., using a prefix: `foo-dev` vs. `bar-dev`, `foo-prod` vs. `bar-prod`, etc.

That is possible to implement by a combination of `environment` and `environment_targets` input variables:

```yaml
environment: foo-dev
environment_targets: foo-dev,foo-staging,foo-prod
```

However, with the current design of the `branch-deploy` action, the IssueOps interface would look like this:

```
.deploy foo foo-dev
.deploy bar bar-dev
```

... which seems inconvenient and unreadable as one has to repeat the project name twice.

I wonder if we could introduce an additional parameter, e.g., `environment_prefix`, that would alter the behavior of the `branch-deploy` action internally so that the action, given an environment `dev` (from issue comment), prefixes it internally with `environment_prefix` and only the prefixed Github environment is used for further processing. In other words, it would be great to somehow separate input environments from Github environments.

**Comment by GrantBirki** [comment]
@bzurkowski I'm not sure if this would exactly solve the issue at hand, but have you looked at using [parameters](https://github.com/github/branch-deploy/blob/main/docs/parameters.md) by any chance? I recently added this feature to the Action and I'm wondering if you could pass in details specific to your environment in your monorepo to gain better control over your deployments in that regards.

Take a look and let me know what ya think! It may work for you or it might not. Worth a read though I think.

**Comment by bzurkowski** [comment]
@GrantBirki I am aware of the parameters feature, but I do not find it sufficient for my case as it does not provide a more readable interface than the one I struggle with right now, i.e., `.deploy app | ENV=dev` vs. `.deploy app app-dev`. Additionally, I perceive the environment as a primary argument and the command subject, whereas the parameters seem to serve more as options that modify the deployment to a certain degree (akin to the distinction between positional arguments and options).

I am trying hard to integrate the branch-deploy action into the mono-repo setup, and I think I am close to achieving a nice process for infrastructure deployment that could be competitive against alternatives.

What I need is a mechanism that allows supplying a simple, unprefixed list of environments to the action, such as `environment_targets: "dev,staging,prod"`. However, the action should handle these as project-namespaced environments, meaning they should be internally processed as `app-dev,app-staging,app-prod`.

That would make a convenient interface for multi-project configurations:

```yaml
- name: Gate branch deployment
  id: branch-deploy
  uses: github/branch-deploy@v7.0.0
  with:
    trigger: .deploy ${{ inputs.project_name }}
    lock_trigger: .lock ${{ inputs.project_name }}
    unlock_trigger: .unlock ${{ inputs.project_name }}
    help_trigger: .help ${{ inputs.project_name }}
    noop_trigger: .plan ${{ inputs.project_name }}
    environment_prefix: ${{ inputs.project_name }}
    environment_targets: ${{ inputs.environments }}
```

Then, one could run gates for multiple projects in a matrix like this:

```yaml
  deploy:
    strategy:
      matrix:
        include:
        - project_name: app
          environments: dev,pepe,demo,prod
        - project_name: cicd
          environments: dev,prod
        - project_name: artifacts
          environments: prod
        - project_name: security
          environments: prod
        - project_name: remote-workplace
          environments: prod
        - project_name: datahub
          environments: prod
```

Alternatively, we could consider adding a `namespace` or `project` input variable to make the interface even more adapted to multi-project configurations.

I am uncertain whether my suggestion aligns with your envisioned development path for the action. However, after reviewing issues in this repository, it appears some users are exploring similar adjustments due to their mono-repo setups (e.g., https://github.com/github/branch-deploy/issues/91).

**Comment by bzurkowski** [comment]
@GrantBirki I am aware of the parameters feature, but I do not find it sufficient for my case as it does not provide a more readable interface than the one I struggle with right now, i.e., `.deploy app | ENV=dev` vs. `.deploy app app-dev`. Additionally, I perceive the environment as a primary argument and the command subject, whereas parameters seem to serve more as options that modify the deployment to a certain degree (akin to the distinction between positional arguments and options).

I am trying hard to integrate the branch-deploy action into the mono-repo setup, and I think I am close to achieving a nice process for infrastructure deployment that could be competitive against alternatives.

What I need is a mechanism that allows supplying a simple, unprefixed list of environments to the action, such as `environment_targets: "dev,staging,prod"`. However, the action should handle these as project-namespaced environments, meaning they should be internally processed as `app-dev,app-staging,app-prod`.

That would make a convenient interface for multi-project configurations:

```yaml
- name: Gate branch deployment
  id: branch-deploy
  uses: github/branch-deploy@v7.0.0
  with:
    trigger: .deploy ${{ inputs.project_name }}
    lock_trigger: .lock ${{ inputs.project_name }}
    unlock_trigger: .unlock ${{ inputs.project_name }}
    help_trigger: .help ${{ inputs.project_name }}
    noop_trigger: .plan ${{ inputs.project_name }}
    environment_prefix: ${{ inputs.project_name }}
    environment_targets: ${{ inputs.environments }}
```

Then, one could run gates for multiple projects in a matrix like this:

```yaml
  deploy:
    strategy:
      matrix:
        include:
        - project_name: app
          environments: dev,,staging,prod
        - project_name: cicd
          environments: dev,prod
        ...
```

Alternatively, we could consider adding a `namespace` or `project` input variable to make the interface even more adapted to multi-project configurations.

I am uncertain whether my suggestion aligns with your envisioned development path for the action. However, after reviewing issues in this repository, it appears some users are exploring similar adjustments due to their mono-repo setups (e.g., https://github.com/github/branch-deploy/issues/91).
