### ISSUE TITLE
Use getBooleanInput

### ISSUE THREAD

**Issue by GrantBirki** [github/branch-deploy#182]
# Use `core. getBooleanInput()`

This issue tracks work to convert all `"true"` / `"false"` string inputs to actual Boolean inputs. There is an function in the Actions core library ([as documented here](https://github.com/actions/toolkit/tree/71a6fceb8c72ffb75c0fe91b273fff1d8a261219/packages/core#inputsoutputs)) that will enable this.

This change will absolutely result in a new **major** semantic release as all users will need to update their Actions inputs where the Booleans are set as strings.

The resulting before / after of this change will look something like this for users:

## Before

```yaml
- name: branch-deploy
  id: branch-deploy
  uses: github/branch-deploy@vX.X.X
  with:
    trigger: ".deploy"
    allow_forks: "true"
```

## After

```yaml
- name: branch-deploy
  id: branch-deploy
  uses: github/branch-deploy@vX.X.X
  with:
    trigger: ".deploy"
    allow_forks: true
```
