### ISSUE TITLE
Unable to lock and unlock specific environments

### ISSUE THREAD

**Issue by bzurkowski** [github/branch-deploy#185]
### Describe the Issue

I am unable to lock and unlock specific deployment environments when using `.lock` and `.unlock` commands:

<img width="681" alt="Screenshot 2023-08-16 at 10 58 46" src="https://github.com/github/branch-deploy/assets/6787563/f967e8ab-a086-460b-a74a-e507b2649cb4">

However, when no specific environment is selected, the default one is successfully unlocked:

<img width="684" alt="Screenshot 2023-08-16 at 10 54 22" src="https://github.com/github/branch-deploy/assets/6787563/997a448b-8404-4f93-ba58-007abc54bcb1">

I am using custom trigger for both `lock` and `unlock` as visible in the attached action configuration.

### Action Configuration

```yaml
- name: Gate branch deployment
  id: branch-deploy
  uses: github/branch-deploy@v7.2.0
  with:
    trigger: .deploy app
    lock_trigger: .lock app
    unlock_trigger: .unlock app
    help_trigger: .help app
    noop_trigger: .plan app
    environment: app-dev
    environment_targets: app-dev,app-staging,app-prod
    production_environment: app-prod
    draft_permitted_targets: app-dev,app-staging,app-prod
    stable_branch: master
    prefix_only: true
    skip_completing: true
```
