### ISSUE TITLE
Is it possible to limit environment deployments to a specific `base_ref`?

### ISSUE THREAD

**Issue by redoz** [github/branch-deploy#193]
### Details

If I want to limit deployments to environment `A` and `B` to PRs against `main`, and deployments to environment `C` to PRs against `release/*`. Is that possible using this action? I figured I'd include a `github.base_ref` check and have two workflows, one for `A` & `B`, and one for `C`, but there's no `base_ref` in an `issue_comment` it seems.

**Comment by GrantBirki** [comment]
:wave: Hello again! Thanks for opening another issue and I would be happy to help.

I read over your issue a few times and my :brain: is getting a bit jumbled around with all the `a`, `b`, and `c` environments.

Do you possibly have a demo, or could you walk me through (in a comment) how this might work in the real world? I am just struggling to understand your message and could use some help visualizing your use case.

Thanks!

**Comment by redoz** [comment]
Yeah even as I wrote the question, I realized it was a bit confusing.  In effect, we have a few different environments, and we use branch-deploy to deploy to those from pull-requests. 
I would like to limit what environments are available for deploying onto, based on the base_ref of the pull request. If you PR targets `main`, you can use environment A, and B, but if your PR targets `release/*` you can only deploy to environment C

I would like to be able to write something like this:
```yaml
    name: 🚀 Deploy
    if: ${{ github.event.issue.pull_request  && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Branch deployment
        id: branch-deploy
        uses: github/branch-deploy@v7.3.0
```
Then I could simply use two different workflows,  but I can't check the `base_ref` because this is an `issue_comment` not a `pull_request` trigger, so I was wondering if there was any kind of built-in support for this? I hope that makes more sense :)
