### ISSUE TITLE
`merge_deploy_mode = true` don't update the current branch deployed

### ISSUE THREAD

**Issue by jhkersul** [github/branch-deploy#201]
### Details

Hi!

Every time a Pull Requests is merged, I'm deploying the stable branch to my `development` environment. 

To do that, I'm using the property `merge_deploy_mode = true` and it works pretty well. However, it doesn't update the current branch deployed.

If I have an opened PR, it still shows as "deployed" even when it's not:

<img width="858" alt="Screenshot 2023-09-04 at 13 17 33" src="https://github.com/github/branch-deploy/assets/1427347/48c53232-730e-4058-bff9-cc472d58bbcd">

Is there any way to fix that?

**Comment by jhkersul** [comment]
Ok, I forgot to pass `environment` to the job. Using something like this worked:

```yml
jobs:
  deploy:
    name: 'Deploy'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Branch Deploy
        id: branch-deploy
        uses: github/branch-deploy@v7.3.1
        with:
          merge_deploy_mode: "true"
          environment: development
# ...
```

<img width="866" alt="Screenshot 2023-09-04 at 14 52 53" src="https://github.com/github/branch-deploy/assets/1427347/0921f599-308b-4a69-a2e9-d534a2cd38fc">
