### ISSUE TITLE
Deploy not occurring due to out-of-date branch when `update_branch` is set to `disable`

### ISSUE THREAD

**Issue by daczarne** [github/branch-deploy#292]
### Describe the Issue

I have a repository where we are using this action to deploy GitHub envs to dev for testing (different teams have different environments for themselves, in this case ours is called `qcommerce`). We have therefore set the `update_branch` to `disable`. Yet, deployments get blocked due to "branch being out of date with main".

![image](https://github.com/user-attachments/assets/e2ad14c1-1e2c-4f28-94c1-0afe45b84178)

### Action Configuration

```yaml
- name: Deploy branch 🚀
  id: deploy_branch
  uses: github/branch-deploy@v9.4.0
  with:
    trigger: .deploy
    reaction: rocket
    environment: qcommerce
    environment_targets: qcommerce
    draft_permitted_targets: qcommerce
    stable_branch: main
    update_branch: disable
    skip_ci: qcommerce
    skip_reviews: qcommerce
```

### Relevant Actions Log Output

Action displayed by the action on the runner (we are using GitHub runners, not self-hosted).

```txt
Run github/branch-deploy@v9.4.0
  with:
    trigger: .deploy
    reaction: rocket
    environment: qcommerce
    environment_targets: qcommerce
    draft_permitted_targets: qcommerce
    update_branch: disable
    skip_ci: qcommerce
    skip_reviews: qcommerce
    github_token: ***
    status: success
    environment_url_in_comment: true
    production_environments: production
    noop_trigger: .noop
    lock_trigger: .lock
    unlock_trigger: .unlock
    help_trigger: .help
    lock_info_alias: .wcid
    permissions: write,maintain,admin
    param_separator: |
    global_lock_flag: --global
    stable_branch: main
    outdated_mode: strict
    required_contexts: false
    checks: all
    allow_forks: true
    admins: false
    admins_pat: false
    merge_deploy_mode: false
    unlock_on_merge_mode: false
    skip_completing: false
    deploy_message_path: .github/deployment_message.md
    sticky_locks: false
    sticky_locks_for_noop: false
    allow_sha_deployments: false
    disable_naked_commands: false
    skip_successful_noop_labels_if_approved: false
    skip_successful_deploy_labels_if_approved: false
✅ comment body starts with trigger: .deploy
🌍 environment: qcommerce
📓 deployment requested on a draft pull request from an allowed environment
⏩ CI checks have been disabled for the qcommerce environment
Warning: The PR branch is behind the base branch by 3 commits
Warning: The PR branch is behind the base branch by 3 commits
Error: ### ⚠️ Cannot proceed with deployment

- mergeStateStatus: `BLOCKED`
- update_branch: `disable`

> I went ahead and updated your branch with `main` - Please try again once this operation is complete
```

### Extra Information

Once we update the branch and re-trigger the workflow, the error goes away (as expected). But we want to avoid this, as this is a mono-repo and we are deploying to a dev env for testing anyways.
