### ISSUE TITLE
Parallell noop deployments from a single comment - .noop dev,uat,prd

### ISSUE THREAD

**Issue by walkerk1980** [github/branch-deploy#310]
### Details

We're currently using branch-deploy for terraform deployments with multiple environment jobs.

```yaml
  comment_parser:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment:
      name: oidc
    steps:
      - name: Parse Issue Comment for Command
        id: branch_deploy
        uses: github/branch-deploy@v9.8.1
        with:
          trigger: ".tf_apply"
          noop_trigger: ".tf_plan"
          permissions: write,admin
          environment_targets: ${{ inputs.target_environments }}
          production_environments: env.PRODUCTION_ENVIRONMENTS
          environment: dev
          skip_ci: dev,uat,tst,tqa,sup
          skip_reviews: dev,uat,tst,tqa,sup
          skip_completing: 'true' # we will complete the deployment manually
      - name: If environment is production, set the TF workspace output to default
        id: set_tf_workspace
        if: ${{ steps.branch_deploy.outputs.continue == 'true' }}
        run: |
          if [ "${{ steps.branch_deploy.outputs.environment }}" == "prd" ]; then
            echo "TF_WORKSPACE=default" >> $GITHUB_OUTPUT
          else
            echo "TF_WORKSPACE=${{ steps.branch_deploy.outputs.environment }}" >> $GITHUB_OUTPUT
          fi
```

We then use the outputs of this job to determine what environments to plan or apply against in subsequent jobs, pretty much like what is laid out in the examples.  

```yaml
  terraform_plan:
    if: ${{ needs.comment_parser.outputs.continue == 'true' && needs.comment_parser.outputs.noop == 'true' }}
    needs: comment_parser
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: ${{ needs.comment_parser.outputs.environment }}
```

We have several non-production environments for each project and sometimes more than one production environment. The environments can vary per project but typically we're talking dev,uat,prd.

We aren't yet using the new enforce deployment order feature, but even if we adopt it, in terraform's case that only makes sense for us on .tf_apply (.deploy) rather than .tf_apply (.noop). We have no real reason to wait to plan against UAT for example because we haven't applied DEV.

In our current process when we open a PR to add a new feature/infra to a project in order to plan we have to create multiple comments to get plans running:

```
.tf_plan dev
```

```
.tf_plan uat
```

```
.tf_plan prd
```

It would be easier for us if we could comment like so:

``` 
.tf_plan dev,uat,prd
```

Then rather than use the "environment: string" output, we'd use the "environments: list" output to run against multiple environments.

We currently do something like this with issues and the actions/command-action

```yaml
  terraform_drift_detection:
    if: ${{ needs.environments.outputs.environments != '[]' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.environments.outputs.environments) }}
```

Is there any chance this would be desirable as a feature?
