### ISSUE TITLE
Allow dynamic environment names

### ISSUE THREAD

**Issue by fabn** [github/branch-deploy#320]
### Details

We're using this action to deploy to dynamic environments, e.g. `https://feature-1234.example.com` where `feature-1234` is the environment name. We use a branch slug to create the env name or allow the user to enter his one via `.deploy to some-env`. 

However I need to hack the action to allow these names by doing some github workflows magic, like:

```yaml
      # Allow to use the custom env name if provided via command (parsed from comment)
      - name: Final Env Name
        id: env
        run: |
          name=${{ steps.custom-env.outputs.result }}

      - uses: github/branch-deploy@v9.9.1
        id: bot
        with:
          trigger: ".deploy"
          environment: ${{ steps.env.outputs.name }}
          # Don't restrict the list of environments to deploy to, to allow usage of free-name environments
          environment_targets: ${{ steps.env.outputs.name }},staging,canary
```

It would be very useful to accept a falsey value for `environment_targets` (or some wildcard chars, or a regex) to allow dynamic env names.

Another option would be to provide an input to skip the `environment_targets` validation for the action.

Thanks.

**Comment by GrantBirki** [comment]
@fabn thank you for this idea! I can certainly see how this could be useful. Would you be able to provide an example yaml snippet of how you might want this to look to satisfy your use case? An example showing your desired end state would be super helpful. Thank you! 🙏

**Comment by fabn** [comment]
> Would you be able to provide an example yaml snippet of how you might want this to look to satisfy your use case?

I guess something like this would be enough for me:

```yaml
      - uses: github/branch-deploy@v9.9.1
        id: bot
        with:
          environment: ${{ steps.env.outputs.name }}
          # Don't restrict the list of environments to deploy to, to allow usage of free-name environments
          environment_targets: 'staging,production,dev-*' 
          # Or a regexp, of course you need to choose between targets and regexp, it's confusing to use both
          environment_regexp: 'dev-.*'
```
