### ISSUE TITLE
Required checks - ignored

### ISSUE THREAD

**Issue by kboro** [github/branch-deploy#362]
### Describe the Issue

Hello,

One of "Required" action is executed after label to PR is applied. Until then deployment shouldnt be possible:

![Image](https://github.com/user-attachments/assets/74aafcfc-043a-4173-9069-336abfd2b103)

However looks like its being ignored and deployment happens:

![Image](https://github.com/user-attachments/assets/18b8a6ba-1d6a-47b0-8e1a-f8b96b9a4b9f)

Why this Check is ignored ?

### Action Configuration

```yaml
 - uses: github/branch-deploy@v10.1.0
   id: branch-deploy
   with:
     trigger: ".deploy"
     noop_trigger: ".noop"
     stable_branch: "main"
     environment_targets: "production,stage,dev"
     environment: "production"
     checks: 'quality_gate'
```
