### ISSUE TITLE
Cannot read properties of undefined (reading body)

### ISSUE THREAD

**Issue by Wiz1991** [github/branch-deploy#62]
![image](https://user-images.githubusercontent.com/45233935/193554194-959fadd3-07f0-4030-9a33-56fbd76d6026.png)
Using the example workflow for ssh, fails on the first step when attempting to run branch-deploy

Version: 3.0.1

**Comment by GrantBirki** [comment]
@Wiz1991 Do you have a link to your workflow where this is failing?

**Comment by Wiz1991** [comment]
@GrantBirki 
No, the repo is private. But here is the entire workflow file.
```yaml
name: branch-deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  issue_comment:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: https://github.com/github/branch-deploy/tree/v2.4.1v2.4.1
        id: branch-deploy
        with:
          trigger: ".deploy"
          reaction: "eyes"
      
      - name: Checkout
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        uses: https://github.com/actions/checkout/tree/7884fcad6b5d53d10323aee724dc68d8b9096a2e7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
      
      - name: SSH Remote Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        uses: https://github.com/appleboy/ssh-action/tree/1d1b21ca96111b1eb4c03c21c14ebb971d2200f61d1b21ca96111b1eb4c03c21c14ebb971d2200f6 # pin@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: npm ci
          ```

**Comment by Wiz1991** [comment]
Heres the full log files tho: 
[logs_21.zip](https://github.com/github/branch-deploy/files/9708518/logs_21.zip)

**Comment by GrantBirki** [comment]
Ah I see a few potential issues here..

First, the `branch-deploy` workflow by design will not run properly on any other workflow type besides the following:

```yaml
on:
  issue_comment:
    types: [created]
```

> see more in the [docs](https://github.com/github/branch-deploy#how-does-it-work-)

When running under either of these contexts...

```yaml
push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
```

... there will be no `body` property available (comment body) for the `branch-deploy` Action to read so it will fail every time. The `branch-deploy` Action can truly only run when triggered from a comment. You should probably put those `push` and `pull_request` workflow triggers into their own workflow and handle them separately.

---

Second, I have not seen this syntax used before:

```yaml
- uses: https://github.com/github/branch-deploy/tree/v2.4.1v2.4.1
```

Its probably valid if its invoking your Action okay but I would suggest one of the following:

```yaml
- uses: github/branch-deploy@v3.0.1
```

or pin to the exact sha

```yaml
- uses: github/branch-deploy@13475966d6676e2eb5825486fd7b8993bb2d6f7c # pin@v3.0.1
```

---

Lastly, `trigger` and `reaction` are currently set to their default values so they can be removed in your case

From this

```yaml
- uses: https://github.com/github/branch-deploy/tree/v2.4.1v2.4.1
  id: branch-deploy
  with:
    trigger: ".deploy"
    reaction: "eyes"
```

to this

```yaml
- uses: github/branch-deploy@13475966d6676e2eb5825486fd7b8993bb2d6f7c # pin@v3.0.1
  id: branch-deploy
```

---

Hopefully that helps! :smiley:
