### ISSUE TITLE
Environment-specific locks

### ISSUE THREAD

**Issue by necropolina** [github/branch-deploy#74]
Would be nice if we could toggle sticky locks for specific environments by providing the environment name after the trigger, such as  `.lock staging` & `.unlock development`. Then the lock should only affect deployments to the locked environment, so that I could lock a branch to `staging`, but still deploy to `development`. A universal lock could still be applied by omitting the environment parameter.

Additionally, it'd be nice to have an action with an environment option that checks if a lock exists. This way we could use these locks when triggering deployments via other methods such as pushes to the main branch.

Something with a pattern like:
```yaml
- name: lock-exists
  id: lock-exists
  uses: github/lock-exists
  with:
    environment: development

- name: deploy
  if: ${{ steps.lock-exists.outputs.exists == 'false' }}
  # deployment script, etc
```

Basically, I'm looking to deploy to all environments on pushes to `main` by default, but omit the deploys to development and staging when they're locked.
