### ISSUE TITLE
Action is not working with "Require deployments to succeed before merging"

### ISSUE THREAD

**Issue by mwatson-x** [github/branch-deploy#81]
I'm trying to get to the stage where I can auto-merge a branch once status checks and deployments to multiple environments have succeeded. I've noticed though that whenever I run `.deploy prd` for an environment, it does not have any impact on the deployment check.

![image](https://user-images.githubusercontent.com/105876008/209940707-46b1a0a6-ae4d-4b25-afa7-88378a80efef.png)

The action step is as follows:

```
      - uses: github/branch-deploy@v3.1.0
        id: branch-deploy
        with:
          trigger: ".deploy"
          environment: nonprod
          environment_targets: nonprod, prd 
```

The three questions I have are:

1. Is this known behaviour?
2. Is there some configuration that I'm not setting?
3. If the branch-deploy action isn't able to update the deployment check correctly, what's the simplest way around the issue? (Separate workflow files per environment?) 

Thanks
