### ISSUE TITLE
Question: How can I deploy a pr to multiple environments (prod and qa) using branch-deploy?

### ISSUE THREAD

**Issue by dgokcin** [github/branch-deploy#92]
Hello and thank you for this action. I think once I customize it for our organization, it will significantly improve our deployment frequency. Below are two different workflows that I use for deploying an ecs service to qa and prod aws accounts. How can I use this action if I want to deploy a pr to first qa environment and then to prod environment? Do I need two workflows? Thanks.

Thanks!

```yml
name: Deploy to Amazon ECS QA Environment
on:
  push:
    branches:
      - develop
    paths-ignore:
      - src/LambdaFunctions/**
      - .github/workflows/scheduled-event-triggers-sam-deploy-qa.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  call-dockerized-build:
    uses: MyOrg/shared-actions/.github/workflows/ci-dockerized-app-build.yml@cloud-367/shared-backend-actions
    name: Call Dockerized Build
    with:
      environment: qa
      region: eu-west-1
      namespace: org
      service_name: fulfillment
      app_dockerfile: docker/app.dockerfile
      pre_release: true
      dry_run: false
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_QA_ROLE_TO_ASSUME_ARN }}
      cert_file: ${{ secrets.QA_CERT_FILE }}
      dhparam_file: ${{ secrets.QA_DHPARAM_FILE }}
      key_file: ${{ secrets.QA_KEY_FILE }}
      gh_packages_user: ${{ secrets.GH_PACKAGES_USER }}
      gh_packages_pat: ${{ secrets.GH_PACKAGES_PAT }}
      application_id: ${{ secrets.APPLICATION_ID }}
      application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

  call-ecs-deploy:
    uses: MyOrg/shared-actions/.github/workflows/cd-ecs.yml@cloud-367/shared-backend-actions
    needs: call-dockerized-build
    name: Call ECS Deploy
    with:
      environment: qa
      region: eu-west-1
      namespace: org
      service_name: fulfillment
      tag: ${{ needs.call-dockerized-build.outputs.tag }}
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_QA_ROLE_TO_ASSUME_ARN }}

  call-post-deployment-status-to-slack:
    uses: MyOrg/shared-actions/.github/workflows/controller-post-ecs-deployment-info-to-slack.yml@cloud-367/shared-backend-actions
    needs: call-ecs-deploy
    name: Call Post Deployment Status to Slack
    with:
      environment: qa
      region: eu-west-1
      namespace: org
      service_name: fulfillment
      slack_channel: "#dev-team"
    secrets: inherit

```

```yml
name: Deploy to Amazon ECS PROD Environment
on:
  push:
    branches:
      - main
    paths-ignore:
      - src/LambdaFunctions/**
      - .github/workflows/scheduled-event-triggers-sam-deploy-prod.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  call-dockerized-build:
    uses: MyOrg/shared-actions/.github/workflows/ci-dockerized-app-build.yml@cloud-367/shared-backend-actions
    name: Call Dockerized Build
    with:
      environment: prod
      region: eu-west-1
      namespace: org
      service_name: fulfillment
      app_dockerfile: docker/prod.app.dockerfile
      pre_release: false
      dry_run: false
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_PROD_ROLE_TO_ASSUME_ARN }}
      cert_file: ${{ secrets.PROD_CERT_FILE }}
      dhparam_file: ${{ secrets.PROD_DHPARAM_FILE }}
      key_file: ${{ secrets.PROD_KEY_FILE }}
      gh_packages_user: ${{ secrets.GH_PACKAGES_USER }}
      gh_packages_pat: ${{ secrets.GH_PACKAGES_PAT }}
      application_id: ${{ secrets.APPLICATION_ID }}
      application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

  call-ecs-deploy:
    uses: MyOrg/shared-actions/.github/workflows/cd-ecs.yml@cloud-367/shared-backend-actions
    needs: call-dockerized-build
    name: Call ECS Deploy
    with:
      environment: prod
      region: eu-west-1
      namespace: org
      service_name: fulfillment
      tag: ${{ needs.call-dockerized-build.outputs.tag }}
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_PROD_ROLE_TO_ASSUME_ARN }}

  call-post-deployment-status-to-slack:
    uses: MyOrg/shared-actions/.github/workflows/controller-post-ecs-deployment-info-to-slack.yml@cloud-367/shared-backend-actions
    needs: call-ecs-deploy
    name: Call Post Deployment Status to Slack
    with:
      environment: prod
      region: eu-west-1
      namespace: org
      service_name: fulfillment
      slack_channel: "#dev-team"
    secrets: inherit

```
